### ISSUE TITLE
Update comparision

### ISSUE THREAD

**Issue by arunoda** [chriswessels/meteor-tupperware#1]
Hi,

After the rise of this package, I've make some improvements to MeteorD and I think may be update the README.

1) Now MeteorD is ~220MB (Since it includes PhantomJS by default)
2) Resulting meteor app image only take additional space for the bundle and node modules (For an example, telescope is ~270MB)
3) We've added built in support for the `--server` flag and having any URL is enough.

**Comment by chriswessels** [comment]
Updated README.
