### ISSUE TITLE
Better Demo

### ISSUE THREAD

**Issue by loffelmacher** [chriswessels/meteor-tupperware#11]
Hi, love that you put this together, thank you! However I'm having some trouble using it. I've created a new meteor app, `cd` into the folder for my app, and ran your Quickstart command. But I don't see anything in my browser. From what I can see, I should be able to see something.

It's also unclear to me if I can run the mongo DB in the same container for development purposes, I think not, it looks like this is aimed more at production/staging only. So a note about this in the README could be useful to others.

**Comment by chriswessels** [comment]
Thanks for your feedback. This project is only for running your app in production.
