### ISSUE TITLE
future.js module throwing exception

### ISSUE THREAD

**Issue by mlschuh** [chriswessels/meteor-tupperware#12]
I've encountered the following error message after building a new image of my test meteor app. 

```
root@docker-staging:~/simple-todos# docker run -e MONGO_URL=mongodb://admin:xxxx@172.24.0.245:xxxx/ smi/tupperwaretest
[-] meteor-tupperware is starting your application with NODE_ENV=production and METEOR_ENV=production...

/output/bundle/programs/server/node_modules/fibers/future.js:278
                        throw(ex);
                              ^
[object Object]
    at Object.Future.wait (/output/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at simple-todos.js:12:9
    at /output/bundle/programs/server/app/simple-todos.js:28:4
    at /output/bundle/programs/server/boot.js:242:10
    at Array.forEach (native)
```

My research points to version 0.10.41 of node being the culprit but I'm a bit lost with anything past that, including the most efficient way to confirm it. I created the image with the process outlined in the root readme.md (ran the shell script, which worked in the end but also threw the error on line 19).

```
root@docker-staging:~/simple-todos# curl https://raw.githubusercontent.com/chriswessels/meteor-tupperware/master/quickstart.sh > /tmp/quickstart.sh && sh /tmp/quickstart.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1565  100  1565    0     0   5561      0 --:--:-- --:--:-- --:--:--  5589

>> meteor-tupperware quickstart script 0.1.2

/tmp/quickstart.sh: 11: /tmp/quickstart.sh: [[: not found
/tmp/quickstart.sh: 11: /tmp/quickstart.sh: -f: not found
] Docker Image Maintainer Information
? Please enter your name: 
mlschuh
/tmp/quickstart.sh: 19: /tmp/quickstart.sh: [[: not found

] Success
```

Any tips on where to start digging?

-Mitch

**Comment by chriswessels** [comment]
Looks like you're running the quickstart in `sh` and not `bash`, which is why you're getting those errors.

Also, you might need to specify the database in your `MONGO_URL`.

e.g. `MONGO_URL=mongodb://admin:xxxx@172.24.0.245:xxxx/database_name`

**Comment by chriswessels** [comment]
@mlschuh, did you figure this out?

**Comment by mlschuh** [comment]
Apologies, other endevours here needed attention.

I got around the running in shell error by not running the command in the README (which has 'sh /tmp/quickstart.sh'). I instead just downloaded the file and then executed /bin/bash /tmp/quickstart to force it to use bash.

The fibers error still persists, however has adjusted slightly. It's now giving useful feedback. I'm working towards resolving that ("Error: Must pass options.rootUrl or set ROOT_URL in the server environment") and will let you know.

**UPDATE:**
Have landed at the following:

```
/output/bundle/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
ReferenceError: require is not defined
```

which, if I'm not mistaken, is something within the project I'm trying to use (the meteor SimpleToDos example). From here, I expect that I'll need to dig through the project to resolve it.
