### ISSUE TITLE
Docker Hub automated builds error 'Directory renamed before its status could be extracted' 

### ISSUE THREAD

**Issue by 0o-de-lally** [chriswessels/meteor-tupperware#17]
@chriswessels I'm really interested in this package. However while testing with DockerHub I get the following error, on automated builds:

```
[-]  No tupperware.json found, using defaults. 
[-]  Downloading Meteor 1.3.2.4 Installer... 
[-]  Installing Meteor 1.3.2.4... 
[!]  While attempting to install Meteor.js, the command: sh /tmp/install_meteor.sh 
[!]  Failed with the exit code 2. The signal was undefined. 
[-]  The task produced the following stderr:
```

In different places I see 'Directory renamed before its status could be extracted' . Any clues how this can be fixed? Thanks!

**Comment by chriswessels** [comment]
Was there any stderr or stdout produced?

**Comment by 0o-de-lally** [comment]
It's dozens of errors like this: 

`tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules: Directory renamed before its status could be extracted`

Have you by chance tested docker hub automated builds?

**Comment by chriswessels** [comment]
@keyscores Did you come right?

**Comment by 0o-de-lally** [comment]
The error was being produced by Docker Cloud. I'm going to retry on Quay.io and give you feedback. Thanks for checking-in.

**Comment by chriswessels** [comment]
@keyscores, I'm going to close for the moment. Let me know if you have further issues. I use tupperware on Quay.io and GCR without any issues.
