### ISSUE TITLE
set env from settings.json file just like tupperware.json

### ISSUE THREAD

**Issue by fangjj** [chriswessels/meteor-tupperware#18]
my meteor project have many env var, so i can't wirte docker -e ...
i hope use settings.json just like mup.

**Comment by rohanray** [comment]
@chriswessels Nice work indeed! Much simpler,cleaner and efficient than mup/mupx. I agree with @fangjj even I would like to see this feature which is basically a feature of core Meteor build system [environment variables and settings](https://guide.meteor.com/deployment.html#environment)

**Comment by chriswessels** [comment]
Hello,

You should bake these into your Dockerfile.

See `ENV` command below:

``` dockerfile
# https://github.com/chriswessels/meteor-tupperware
FROM quay.io/chriswessels/meteor-tupperware

# (optional) Bake runtime options into your image
ENV MONGO_URL="mongodb://url" MONGO_OPLOG_URL="mongodb://oplog_url" ROOT_URL="http://yourapp.com"
```

Chris

**Comment by rohanray** [comment]
@chriswessels Thanks for looking into this! I have done that for now, but it's not feasible for a large number of env variables, especially when we have json to set as a few env variables for e.g. hooking up facebook, twitter etc. requires setting up these as a service object with app id and secret token. Is there any way the package can be modified to take a "json file" which has all environment variables set-up.

My sample settings.json file per se:

`{
  "sendgridkey": "smtp://apikey:asd@smtp.sendgrid.net:587",
  "adminData": {
    "email": "qwe@asdasdcom",
    "password": "xxx"
  },
  "services": [{
    "service": "facebook",
    "credentials": {
      "appId": "xxx",
      "secret": "yyy"
    }
  }, {
    "service": "twitter",
    "credentials": {
      "consumerKey": "xxx",
      "secret": "yyy"
    }
  }, {
    "service": "google",
    "credentials": {
      "clientId": "xxx-.apps.googleusercontent.com",
      "secret": "yyy"
    }
  }],
  "utils": {
    "domain": "http://localhost:3000/",
    "supportEmail": "qwe@asdasdcom",
    "siteName": "support admin",
    "from": "Support Sp. <support@qweasd.com>"
  }
}`

Thanks,
Rohan.

**Comment by chriswessels** [comment]
@rohanray You can use multiple `ENV` lines in the Dockerfile.

Otherwise, I welcome a PR adding the functionality you speak of.

Best,
Chris

**Comment by rohanray** [comment]
Thanks Chris!

Let me see if I can get this functionality running, then I will send a PR.

Thanks
Rohan
