### ISSUE TITLE
How to set ROOT_URL, MONGO_URL  MONGO_OPLOG_URL and build error

### ISSUE THREAD

**Issue by scheung38** [chriswessels/meteor-tupperware#22]
ENV MONGO_URL="mongodb://url" MONGO_OPLOG_URL="mongodb://oplog_url" ROOT_URL="http://yourapp.com"

How to get/set the ROOT_URL, MONGO_URL,  MONGO_OPLOG_URL

tupperware.json:

{
  "dependencies": {
    "phantomJs": false,
    "imageMagick": false
  },
"preBuildCommands": ["sudo apt-get update && sudo apt-get install -y  --force=yes build-essential python"],
  "postBuildCommands": [],
  "buildOptions": {
    "mobileServerUrl": false,
    "additionalFlags": false
  }
}

$ docker build -t scheung/spark2acs .
Sending build context to Docker daemon 356.9 MB
Step 1 : FROM quay.io/chriswessels/meteor-tupperware
# Executing 2 build triggers...

Step 1 : COPY ./ /app
Step 1 : RUN sh /tupperware/scripts/on_build.sh
 ---> Running in cc53a398420d

  _  
 | |_ _   _ _ __  _ __   ___ _ ____      ____ _ _ __ ___ 
 | **| | | | '_ | '_ \ / _ \ '**\ \ /\ / / _` | '__/ _ \
 | |_| |_| | |_) | |_) |  **/ |   \ V  V / (_| | | |  __/
  \**|__,_| .**/| .**/ _**|_|    \_/_/ \**,_|_|  ___|
           |_|   |_|                                     

[-]  github.com/chriswessels/meteor-tupperware (tupperbuild v1.0.0)

[-]  Settings in tupperware.json registered.
[-]  Downloading Meteor 1.3.2.4 Installer...
[-]  Installing Meteor 1.3.2.4...
[-]  Running pre-build commands...
[!]  While attempting to run pre-build command, the command: sudo apt-get update && sudo apt-get install -y  --force=yes build-essential python
[!]  Failed with the exit code 100. The signal was null.
[-]  The task produced the following stdout:
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://httpredir.debian.org jessie InRelease
Get:2 http://httpredir.debian.org jessie-updates InRelease [142 kB]
Get:3 http://security.debian.org jessie/updates/main amd64 Packages [387 kB]
Get:4 http://httpredir.debian.org jessie Release.gpg [2373 B]
Get:5 http://httpredir.debian.org jessie Release [148 kB]
Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:7 http://httpredir.debian.org jessie/main amd64 Packages [9032 kB]
Fetched 9792 kB in 16s (586 kB/s)
Reading package lists...

[-]  The task produced the following stderr:
E: Command line option --force=yes is not understood

**Comment by chriswessels** [comment]
`--force=yes` is not the correct flag. Try `-y` instead.

If you want to deploy with Docker, I would recommend reading the docs here: 
https://docs.docker.com/engine/understanding-docker/
https://docs.docker.com/engine/reference/builder/
https://docs.docker.com/engine/reference/run/

Also, take a look at the deployment guide here:
https://guide.meteor.com/deployment.html#custom-deployment

It speaks about what the environment variables are for.

**Comment by scheung38** [comment]
What values to set  ROOT_URL, MONGO_URL, MONGO_OPLOG_URL

**Comment by chriswessels** [comment]
Look at the Meteor documentation @scheung38. I can't learn for you.

**Comment by scheung38** [comment]
ENV MONGO_URL="mongodb://127.0.0.1:3001/meteor" 

MONGO_OPLOG_URL="mongodb://oplogger:PasswordForOplogger@mongo-server-1.example.com,mongo-server-2.example.com,mongo-server-3.example.com/local?authSource=admin&replicaSet=replicaSetName" 

ROOT_URL="http://app.com"

?

Cheers

**Comment by chriswessels** [comment]
@scheung38 
MONGO_URL should point to your production Mongo server, not a local Meteor server's embedded Mongo (which is what the URL would do).

Leave out MONGO_OPLOG_URL for now, you don't need it.

ROOT_URL is correct.

Deploying with Docker has advantages, but is particularly complex. I think you should consider Meteor Galaxy (a hosted service), or Meteor Up: https://github.com/arunoda/meteor-up

**Comment by scheung38** [comment]
DockerFile:

ENV MONGO_OPLOG_URL="mongodb://oplogger:oplogger@127.0.0.1:27017/local?authSource=admin"

$  docker build -t scheung/spark2acs .

After built

Successfully built b133c66bf09b

$ brew services restart mongodb
Stopping `mongodb`... (might take a while)
==> Successfully stopped `mongodb` (label: homebrew.mxcl.mongodb)
==> Successfully started `mongodb` (label: homebrew.mxcl.mongodb)

Tried : 

$ docker run --rm -e MONGO_URL="mongodb://127.0.0.1:3001/future_tasks"    -p 8080:80 scheung/spark2acs

Error: failed to connect to [127.0.0.1:3001]

$ docker run --rm -e MONGO_URL="mongodb://127.0.0.1:3001/meteor"    -p 8080:80 scheung/spark2acs

Error: failed to connect to [127.0.0.1:3001]

$ docker run --rm -e MONGO_URL="mongodb://127.0.0.1:27017/future_tasks" -p 8080:80 scheung/spark2acs

Error: failed to connect to [127.0.0.1:27017]
