### ISSUE TITLE
Tupperware just hangs after [-] Building your app...

### ISSUE THREAD

**Issue by badmark** [chriswessels/meteor-tupperware#23]
```
[-]  github.com/chriswessels/meteor-tupperware (tupperbuild v1.0.0)

[-]  Settings in tupperware.json registered.
[-]  Downloading Meteor 1.4.1.1 Installer...
[-]  Installing Meteor 1.4.1.1...
[-]  Building your app...

```

Projects builds and works locally and when deployed to VPS. Cannot for the life of me figure out why it ends here and goes no further. No error message just hangs.

Any help is appreciated!

**Comment by ianmartorell** [comment]
How long did you wait? For me, it takes over 15min to build.

**Comment by badmark** [comment]
My last attempt is going on 3 hours.

**Comment by ianmartorell** [comment]
then there's definitely something wrong...

**Comment by badmark** [comment]
I wish I knew, tailing Docker logs gives me nothing. Runs fine locally. Scratching my head. Tried with Meteord and kept getting the node-gyp build error. At my wits end! :/

**Comment by ianmartorell** [comment]
I would try and build an image using a bare Meteor app, to rule out whether it's a problem with your build process or with your specific app.

**Comment by badmark** [comment]
Starting that now, will report back shortly. Thank you.

**Comment by badmark** [comment]
Simple one page meteor app with no real logic built. Can I turn on some more verbose logging to track down why my 'not so big' Meteor app won't build?

**Comment by chriswessels** [comment]
Badmark, it's possibly a problem with one of the npm modules that has native extensions that need to be compiled (which is why it works when compiling on OS X).

To debug, try building manually inside a docker container and see what happens.

**Comment by dperetti** [comment]
Same pain happening here...
When each attempt to build lasts a couple hours, it would definitely be nice to always have a build log !

**Comment by chriswessels** [comment]
@dperetti I hear you. Unfortunately I no longer use Meteor for projects, so the time I have to sort issues like these out is very constrained.

PRs welcome!

**Comment by dperetti** [comment]
Neither do I (well, I wish)... therefore the massive pain :-)
