### ISSUE TITLE
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable

### ISSUE THREAD

**Issue by 0o-de-lally** [chriswessels/meteor-tupperware#24]
Building on quay.io. 
Seems to be an issue with NPM dependencies, which require gyp, and hence python.

_ | |_ _ _ _ __ _ __ ___ _ ____ ____ _ _ __ ___ | **| | | | '_ | '_ \ / _ \ '**\ \ /\ / / _` | '__/ _ \ | |_| |_| | |_) | |_) | **/ | \ V V / (_| | | | __/ \**|__,_| .**/| .**/ _**|_| \_/_/ \**,_|_| ___| |_| |_| [-] github.com/chriswessels/meteor-tupperware (tupperbuild v1.0.0) [-] No tupperware.json found, using defaults. [-] Downloading Meteor 1.3.2.4 Installer...
13[-] Installing Meteor 1.3.2.4...
14[-] Building your app...
15[-] Installing npm dependencies for your app...
16[!] While attempting to install your application's npm dependencies, the command: npm install
17[!] Failed with the exit code 1. The signal was null.
18[-] The task produced the following stdout:
19 > fibers@1.0.8 install /output/bundle/programs/server/node_modules/fibers > node build.js || nodejs build.js
20[-] The task produced the following stderr:
21npm WARN package.json meteor-dev-bundle@0.0.0 No description npm WARN package.json meteor-dev-bundle@0.0.0 No repository field. npm WARN package.json meteor-dev-bundle@0.0.0 No README data npm WARN package.json meteor-dev-bundle@0.0.0 No license field. gyp ERR! configure error gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable. gyp ERR! stack at failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:401:14) gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:330:11 gyp ERR! stack at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:69:16) gyp ERR! stack at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:81:29) gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/which/which.js:90:16 gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5 gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5 gyp ERR! stack at FSReqWrap.oncomplete (fs.js:82:15) gyp ERR! System Linux 4.4.6-coreos gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" gyp ERR! cwd /output/bundle/programs/server/node_modules/fibers gyp ERR! node -v v4.4.7 gyp ERR! node-gyp -v v3.3.1 gyp ERR! not ok Build failed sh: 1: nodejs: not found npm ERR! Linux 4.4.6-coreos npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" npm ERR! node v4.4.7 npm ERR! npm v2.15.8 npm ERR! file sh npm ERR! code ELIFECYCLE npm ERR! errno ENOENT npm ERR! syscall spawn npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js` npm ERR! spawn ENOENT npm ERR! npm ERR! Failed at the fibers@1.0.8 install script 'node build.js || nodejs build.js'. npm ERR! This is most likely a problem with the fibers package, npm ERR! not with npm itself. npm ERR! Tell the author that this fails on your system: npm ERR! node build.js || nodejs build.js npm ERR! You can get information on how to open an issue for this project with: npm ERR! npm bugs fibers npm ERR! Or if that isn't available, you can get their info via: npm ERR! npm ERR! npm owner ls fibers npm ERR! There is likely additional logging output above. npm ERR! Please include the following file with any support request: npm ERR! /output/bundle/programs/server/npm-debug.log [-] Container build failed. meteor-tupperware is exiting... 9/27/2016, 2:35:04 PM
22Removing intermediate container 73e0c533eb90
23Removing intermediate container f4224362eaf4

**Comment by 0o-de-lally** [comment]
See the docker repo here:
https://quay.io/repository/keyscores/meteord_test?tab=builds

**Comment by chriswessels** [comment]
@keyscores The latest version of Tupperware is only compatible with Meteor 1.4+

If you want to use an older version of Meteor, you need the following in preBuildCommands in your tupperware.json:

```
{
  "dependencies": {
    "phantomJs": false,
    "imageMagick": false
  },
  "preBuildCommands": ["sudo apt-get update && sudo apt-get install -y build-essential python"],
  "postBuildCommands": [],
  "buildOptions": {
    "mobileServerUrl": false,
    "additionalFlags": false
  }
}
```

**Comment by 0o-de-lally** [comment]
OK thanks. Related question: will tupperware rebuild the npm dependencies
for the host architecture? That is, I have npm dependencies that have
binaries built for OSX, which would have to be recompiled for Ubuntu. Any
thoughts?

**Comment by chriswessels** [comment]
Yes, it should do

**Comment by keyscores** [comment]
I've got it to build. Though, I'm getting an error in Docker on 'docker run', probably unrelated to this github issue:

Error (500 Server Error: Internal Server Error ("Get https://quay.io/v2/keyscores/meteord_test/manifests/latest: Error parsing HTTP response: invalid character 'T' looking for beginning of value: "Too many login attempts. \nPlease reset your Quay password and try again.""))
