### ISSUE TITLE
How to add Meteor dependencies in Docker ?

### ISSUE THREAD

**Issue by catherineHR** [chriswessels/meteor-tupperware#26]
I have a project depending on various Meteor packages. On my computer, I've added them using the following command: 
`meteor add raix:ui-dropped-event`
Where should I specify the package dependencies when building my Meteor docker? 
I try to modify the bower.json as follows:
`"dependencies": {                                                                                                                
"raix:ui-dropped-event": "=0.0.7"   
`
but the following error raised:
[-]  Building your app...
[!]  While attempting to build your application, the command: meteor build --directory /output --architecture os.linux.x86_64  
[!]  Failed with the exit code 1. The signal was null.
[-]  The task produced the following stdout:  
Bower:  { [Error: Package paper not found] stack: [Getter] }
Bower:  { [Error: Package raix:ui-dropped-event=raix:ui-dropped-event not found] stack: [Getter] }

Thanks for your advice!

**Comment by chriswessels** [comment]
Hi @catherineHR, unfortunately I'm no longer maintaining this package. If you're looking for an alternative, I'd highly recommend https://github.com/jshimko/meteor-launchpad. Thanks for using tupperware.
