### ISSUE TITLE
Error : meteor build exit code: 1

### ISSUE THREAD

**Issue by Jayuda** [chriswessels/meteor-tupperware#3]
hello Mr. @chriswessels 
I am try with quickstart. but shows error like this :

Building your app...
An error occurred: meteor build exit code: 1
! Failure. Exiting...
The command '/bin/sh -c sh /tupperware/scripts/on_build.sh' returned a non-zero code: 1

Any idea about it ?
Thanks you verry much

**Comment by petrometro** [comment]
+1

**Comment by kelbongoo** [comment]
This just means your meteor build is failing... to debug just run 

```
meteor build --architecture os.linux.x86_64 .
```

locally and you'll see what the error is

**Comment by chriswessels** [comment]
Hi there,

Please try again with the latest version of meteor-tupperware. It should now give you details about why your build failed.

Chris
