### ISSUE TITLE
TypeError : cannot read property '1' of null

### ISSUE THREAD

**Issue by renkaze57** [chriswessels/meteor-tupperware#30]
Hi,

I have the following issue while creating a docker image of a meteor project : 

Sending build context to Docker daemon 42.33 MB
Step 1 : FROM quay.io/chriswessels/meteor-tupperware
# Executing 2 build triggers...
Step 1 : COPY ./ /app
 ---> Using cache
Step 1 : RUN sh /tupperware/scripts/on_build.sh
 ---> Running in 41c3c7a311a8

[-]  github.com/chriswessels/meteor-tupperware (tupperbuild v1.0.0)

[-]  No tupperware.json found, using defaults.
/tupperware/tupperbuild/main.js:238
  meteorVersion = matches[1];
                         ^

TypeError: Cannot read property '1' of null
    at downloadMeteorInstaller (/tupperware/tupperbuild/main.js:238:26)
    at /tupperware/tupperbuild/node_modules/async/lib/async.js:607:21
    at /tupperware/tupperbuild/node_modules/async/lib/async.js:246:17
    at iterate (/tupperware/tupperbuild/node_modules/async/lib/async.js:146:13)
    at /tupperware/tupperbuild/node_modules/async/lib/async.js:157:25
    at /tupperware/tupperbuild/node_modules/async/lib/async.js:248:21
    at /tupperware/tupperbuild/node_modules/async/lib/async.js:612:34
    at /tupperware/tupperbuild/main.js:227:5
    at /tupperware/tupperbuild/node_modules/async/lib/async.js:607:21
    at /tupperware/tupperbuild/node_modules/async/lib/async.js:246:17
The command '/bin/sh -c sh /tupperware/scripts/on_build.sh' returned a non-zero code: 1

Can anyone give me some help or tips ? 
Thanks a lot !

**Comment by rohanray** [comment]
@Renkaze Faced this issue just today. Please ensure there's an empty (or blank) line in the end of file. That worked for me. I think its to do with the regex which reads the file to download the specified meteor version.

I know it's an old issue, however, might help someone in the same position.

**Comment by chriswessels** [comment]
Hi @Renkaze, unfortunately I'm no longer maintaining this package. If you're looking for an alternative, I'd highly recommend https://github.com/jshimko/meteor-launchpad. Thanks for using tupperware.
