### ISSUE TITLE
Deployment to Docker Hangs

### ISSUE THREAD

**Issue by ghost** [chriswessels/meteor-tupperware#31]
Hi,

When I try to do a docker run in my local mac, it works. However, when I run it on docker linux it hangs...

[-] meteor-tupperware is starting your application with NODE_ENV=production and METEOR_ENV=production on port 80...
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.

I tried a docker on ubuntu and docker swarm on Azure. Same problem.

**Comment by chriswessels** [comment]
Hi @rodinsandrino, unfortunately I'm no longer maintaining this package. If you're looking for an alternative, I'd highly recommend https://github.com/jshimko/meteor-launchpad. Thanks for using tupperware.
