### ISSUE TITLE
How to add other binary's

### ISSUE THREAD

**Issue by kjetilge** [chriswessels/meteor-tupperware#7]
Could you provide a recipe for adding other binaries, like ffmpeg ?

**Comment by markshust** [comment]
Do you mean with `apt-get`? Just use this as base image and build your own image from it.

**Comment by chriswessels** [comment]
@markoshust is spot on. Just add some `RUN` directives to your `Dockerfile` to install the necessary binaries.

```
FROM quay.io/chriswessels/meteor-tupperware

RUN apt-get update && \
         apt-get install ffmpeg
```

Chris

**Comment by chriswessels** [comment]
Just to add to this prior to closing, if you need some binaries in the image PRIOR to tupperware building your Meteor app (which is generally not the case), you can use `preBuildCommands` in `tupperware.json`.

I'd create a shell script (`install_deps.sh` in this example) in the `private` folder that installs whatever you need via apt-get. Then configure your `tupperware.json` to look like this:

```
{
  "preBuildCommands": ["sh private/install_deps.sh"]
}
```

This will run your shell script prior to building your app.

Chris
