### ISSUE TITLE
SMB Hash with Bcrypt

### ISSUE THREAD

**Issue by scottbrumley** [chriswessels/meteor-tupperware#8]
Hi I'm using tupperware and I'm hashing data with Meteor.npmRequire('smbhash').nthash;   When I run the container I get the below message.  Has anyone run into this?  I've solved it in the past removing bcrypt and using "npm install bcrypt" to reinstall but I'd rather not install npm in this optimized image. 

Exception while invoking method 'hashit' Error: Can't find npm module 'smbhash'. Did you forget to call 'Npm.depends' in package.js within the 'npm-container' package?

Thanks for any help.

**Comment by chriswessels** [comment]
Hi @scottbrumley, `npm` is already in the container as it comes with Node.js. I'd suggest trying to `npm install bcrypt` in a `preBuildCommands` script. See README.md.

**Comment by scottbrumley** [comment]
Awesome perfect.  Is there some way to specify where the tupperware.json is located?  I put it next to the dockerfile but it shows in the output that it is not finding it.

Sincerely,
Scott Brumley - mobile
Aruba Certified Mobility Professional

Network Strategies, Inc

**Comment by chriswessels** [comment]
@scottbrumley Unfortunately not. Could you please share `ls` and the output from `docker build`.

**Comment by scottbrumley** [comment]
## Project Folder

drwxr-xr-x 1 vagrant vagrant  238 Nov 27 12:51 client
drwxr-xr-x 1 vagrant vagrant  170 Nov 17 01:31 collections
-rw-r--r-- 1 vagrant vagrant   78 Dec 20 00:55 Dockerfile
drwxr-xr-x 1 vagrant vagrant  136 Dec  6 16:53 lib
-rw-r--r-- 1 vagrant vagrant    0 Nov 22 14:07 menu.html
drwxr-xr-x 1 vagrant vagrant  204 Nov 27 22:44 node_modules
drwxr-xr-x 1 vagrant vagrant  340 Dec 17 06:42 packages
-rw-r--r-- 1 vagrant vagrant   45 Dec 17 06:25 packages.json
drwxr-xr-x 1 vagrant vagrant  204 Dec 18 09:18 private
drwxr-xr-x 1 vagrant vagrant  204 Nov 27 12:50 public
-rw-r--r-- 1 vagrant vagrant 1534 Dec 14 13:06 Readme.md
drwxr-xr-x 1 vagrant vagrant  238 Dec 16 10:26 server
-rw-r--r-- 1 vagrant vagrant   38 Nov 27 21:22 smart.json
-rw-r--r-- 1 vagrant vagrant  282 Nov 27 21:22 smart.lock
-rw-r--r-- 1 vagrant vagrant  254 Dec 18 09:00 tupperware.json
-rw-r--r-- 1 vagrant vagrant 3152 Dec  8 13:19 Vagrantfile
-rw-r--r-- 1 vagrant vagrant 1440 Nov 29 21:40 wt-start-page.iml

## From the Build with "RUN ls" in Dockerfile

==> Building Docker image for wt-start-page:green
Sending build context to Docker daemon   206 MB
Step 1 : FROM quay.io/chriswessels/meteor-tupperware

# Executing 2 build triggers...

Step 1 : COPY ./ /app
Step 1 : RUN sh /tupperware/scripts/on_build.sh
 ---> Running in 1ee3055d8223

  _  
 | |_ _   _ _ __  _ __   ___ _ ____      ____ _ _ __ ___ 
 | **| | | | '_ | '_ \ / _ \ '**\ \ /\ / / _` | '__/ _ \
 | |_| |_| | |_) | |_) |  **/ |   \ V  V / (_| | | |  __/
  \**|__,_| .**/| .**/ _**|_|    \_/_/ \**,_|_|  ___|
           |_|   |_|                                     

[-]  github.com/chriswessels/meteor-tupperware (tupperbuild v1.0.0)

[-]  No tupperware.json found, using defaults.
[-]  Downloading Meteor 1.2.1 Installer...
[-]  Installing Meteor 1.2.1...
[-]  Building your app...
[-]  Installing npm dependencies for your app...
[-]  Performing final image cleanup...
[-]  Success!
 ---> 8f5658cc6ecd
Removing intermediate container 1ee3055d8223
Removing intermediate container 396b25f31a6e
Step 2 : RUN ls
 ---> Running in 9eb30e650d0f
app
bin
boot
dev
etc
home
lib
lib64
media
mnt
opt
output
proc
root
run
sbin
selinux
srv
sys
tmp
tupperware
usr
var
 ---> 2a39d489604d
Removing intermediate container 9eb30e650d0f
Successfully built 2a39d489604d

**Comment by scottbrumley** [comment]
I couldn't get the tupperware.json to work, but I did put **npm install smbhash** into the Dockerfile and all is well.
