### ISSUE TITLE
Docker ignore file should be updated

### ISSUE THREAD

**Issue by dperetti** [chriswessels/meteor-tupperware#9]
Running the latest versions of meteor and npm-container, I had build issues running occurring only on Docker Hub.
Eventually found out they were caused by some `packages/npm-container/.npm` build folder.

Using this `.dockerignore` file fixed my problems :

```
.meteor/local
packages/*/.build*
packages/*/.npm*
```

**Comment by chriswessels** [comment]
Thanks @dperetti! Will release update now.
